---
title: "Simple document"
output: github_document
---

```{r}
library(tidyverse)
library(readxl) # For XLSX import
library(haven) # for SAS files
```


Let's import the  `FAS_Litters.csv` csv.

```{r}
litters_df = 
  read_csv("data/FAS_litters.csv")

litters_df =
  janitor::clean_names(litters_df) #upper case converted to lwer, spaces to underscores, etc
```

Import the same dataset using an absolute path.

```{r, eval = FALSE}
litters_df_abs = 
  read_csv("/Users/JML/Desktop/POR/Fall 2023/p8105/p8105/p8105_data_wrangling_I/data/FAS_litters.csv")

litters_df_abs =
  janitor::clean_names(litters_df_abs) #upper case converted to lwer, spaces to underscores, etc

litters_df_abs
```

# Import pups dataset
## via relative pathway

```{r}
pups_df = 
  read_csv("data/FAS_pups.csv")

pups_df =
  janitor::clean_names(pups_df)

pups_df
```

## via absolute pathway

```{r}
pups_df_abs = 
  read_csv("/Users/JML/Desktop/POR/Fall 2023/p8105/p8105/p8105_data_wrangling_I/data/FAS_pups.csv")

pups_df_abs =
  janitor::clean_names(pups_df_abs)

pups_df_abs
```

# Look at the data
```{r}
litters_df # first 10 rows

head(litters_df) #first 6 rows

tail(litters_df) # last 6 rows
```

To look at the whole dataset you can use `view`
```{r, eval = FALSE}
View(litters_df)
```

## Look at a data summary
```{r}
str(litters_df)

skimr::skim(litters_df)
```

## Options in read_*
```{r}
litters_df =
  read_csv("data/FAS_litters.csv",
           skip = 10, #skip 10 rows
           col_names = FALSE #doesn't use row 11 to get names
  )

litters_df
```

Look at NA values.

```{r}
litters_df = 
  read_csv("data/FAS_litters.csv",
           na = c("NA", 19)
           )

litters_df
```

Column types
```{r}
litters_df =
  read_csv("data/FAS_litters.csv",
           col_types = 
             cols(
               Group = col_factor()
             )
           )

litters_df

litters_df =
  read_csv("data/FAS_litters.csv",
           col_types = 
             cols(
               `GD0 weight` = col_character()
             )
           )

```

## Other file types

import a xlsx file first.

```{r}
mlb_df =
  read_excel("data/mlb11.xlsx") #read in as a tibble, can do similiar modifications as we did above

```

Import a SAS file.
```{r}
pulse_df = 
  read_sas("data/public_pulse_data.sas7bdat")

pulse_df
```

## Base R ...

Don't do this for class.

```{r, eval = FALSE}
litters_df = 
  read.csv("data/FAS_litters.csv")  #when use read.csv imports as df instead of tibble, and default is to print ENTIRE DF, with R DF using $ you can actually pull without whole thing, 'partial matching', but can cause issues later
```

```{r}
litters_df_cleaned = 
  read_csv("data/FAS_litters.csv")

litters_df_cleaned = 
  janitor::clean_names(litters_df_cleaned)

write_csv(litters_df_cleaned, "data/litters_cleaned.csv") #to output, using relative path
```

